-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria_equipo
(
    id_categoria integer NOT NULL,
    nombre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_equipo_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    no_empleado integer NOT NULL,
    a_paterno character varying(20) COLLATE pg_catalog."default" NOT NULL,
    a_materno character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cargo character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT empleado_pkey PRIMARY KEY (no_empleado)
);

CREATE TABLE IF NOT EXISTS public.empleado_proyecto
(
    no_empleado integer,
    id_proyecto integer
);

CREATE TABLE IF NOT EXISTS public.equipo
(
    folio_equipo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    hostname character varying(10) COLLATE pg_catalog."default",
    perfil character varying(25) COLLATE pg_catalog."default" NOT NULL,
    mac character varying(17) COLLATE pg_catalog."default" NOT NULL,
    no_serie character varying(15) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default",
    estatus character varying(10) COLLATE pg_catalog."default",
    id_tipo integer,
    id_modelo integer,
    CONSTRAINT equipo_pkey PRIMARY KEY (folio_equipo),
    CONSTRAINT equipo_hostname_key UNIQUE (hostname)
);

CREATE TABLE IF NOT EXISTS public.inventario
(
    id_inventario integer NOT NULL,
    estado_actual character varying(25) COLLATE pg_catalog."default",
    fecha_resgurdo date,
    fecha_fin date,
    no_empleado integer,
    folio_equipo character varying(10) COLLATE pg_catalog."default",
    id_uni_admin integer,
    id_resguardo integer,
    CONSTRAINT inventario_pkey PRIMARY KEY (id_inventario)
);

CREATE TABLE IF NOT EXISTS public.modelo_equipo
(
    id_modelo integer NOT NULL,
    marca character varying(15) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT modelo_equipo_pkey PRIMARY KEY (id_modelo)
);

CREATE TABLE IF NOT EXISTS public.movimiento
(
    id_movimiento integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    tipo character varying(10) COLLATE pg_catalog."default",
    descripcion character varying(30) COLLATE pg_catalog."default",
    folio_equipo character varying(10) COLLATE pg_catalog."default",
    no_empleado integer,
    id_proyecto integer,
    CONSTRAINT movimiento_pkey PRIMARY KEY (id_movimiento)
);

CREATE TABLE IF NOT EXISTS public.proyecto
(
    id_proyecto integer NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    estatus character varying(10) COLLATE pg_catalog."default",
    no_empleado integer,
    CONSTRAINT proyecto_pkey PRIMARY KEY (id_proyecto)
);

CREATE TABLE IF NOT EXISTS public.resguardo
(
    id_resguardo integer NOT NULL,
    feha_resguardo date NOT NULL,
    estatus character varying(10) COLLATE pg_catalog."default",
    no_empleado integer,
    id_uni_admin integer,
    CONSTRAINT resguardo_pkey PRIMARY KEY (id_resguardo)
);

CREATE TABLE IF NOT EXISTS public.resguardo_equipo
(
    id_resguardo integer,
    folio_equipo character varying(10) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.tipo_equipo
(
    id_tipo integer NOT NULL,
    nombre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    id_categoria integer,
    CONSTRAINT tipo_equipo_pkey PRIMARY KEY (id_tipo)
);

CREATE TABLE IF NOT EXISTS public.unidad_admin
(
    id_uni_admin integer NOT NULL,
    ubicacion character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    siglas character varying(10) COLLATE pg_catalog."default" NOT NULL,
    piso character varying(8) COLLATE pg_catalog."default",
    no_empleado integer NOT NULL,
    CONSTRAINT unidad_admin_pkey PRIMARY KEY (id_uni_admin)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario integer NOT NULL,
    rol character varying(15) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(25) COLLATE pg_catalog."default" NOT NULL,
    estatus character varying(20) COLLATE pg_catalog."default",
    no_empleado integer,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.empleado_proyecto
    ADD CONSTRAINT empleado_proyecto_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyecto (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.empleado_proyecto
    ADD CONSTRAINT empleado_proyecto_no_empleado_fkey FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipo
    ADD CONSTRAINT equipo_id_modelo_fkey FOREIGN KEY (id_modelo)
    REFERENCES public.modelo_equipo (id_modelo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipo
    ADD CONSTRAINT equipo_id_tipo_fkey FOREIGN KEY (id_tipo)
    REFERENCES public.tipo_equipo (id_tipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT inventario_folio_equipo_fkey FOREIGN KEY (folio_equipo)
    REFERENCES public.equipo (folio_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT inventario_id_resguardo_fkey FOREIGN KEY (id_resguardo)
    REFERENCES public.resguardo (id_resguardo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT inventario_id_uni_admin_fkey FOREIGN KEY (id_uni_admin)
    REFERENCES public.unidad_admin (id_uni_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT inventario_no_empleado_fkey FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT movimiento_folio_equipo_fkey FOREIGN KEY (folio_equipo)
    REFERENCES public.equipo (folio_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT movimiento_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyecto (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento
    ADD CONSTRAINT movimiento_no_empleado_fkey FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proyecto
    ADD CONSTRAINT proyecto_no_empleado_fkey FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resguardo
    ADD CONSTRAINT resguardo_id_uni_admin_fkey FOREIGN KEY (id_uni_admin)
    REFERENCES public.unidad_admin (id_uni_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resguardo
    ADD CONSTRAINT resguardo_no_empleado_fkey FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resguardo_equipo
    ADD CONSTRAINT resguardo_equipo_folio_equipo_fkey FOREIGN KEY (folio_equipo)
    REFERENCES public.equipo (folio_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resguardo_equipo
    ADD CONSTRAINT resguardo_equipo_id_resguardo_fkey FOREIGN KEY (id_resguardo)
    REFERENCES public.resguardo (id_resguardo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tipo_equipo
    ADD CONSTRAINT tipo_equipo_id_categoria_fkey FOREIGN KEY (id_categoria)
    REFERENCES public.categoria_equipo (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unidad_admin
    ADD CONSTRAINT no_empleado FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario
    ADD CONSTRAINT no_empleado FOREIGN KEY (no_empleado)
    REFERENCES public.empleado (no_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;